version: "3"
services:
  nginx:
    image: darren:nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "30015:80"
    command: [nginx, "-g", "daemon off;"]
