version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf # nginx 기본 설정
      - ./conf.d:/etc/nginx/conf.d # nginx.conf에 include되는 block
    ports:
      - "30015:80"
    command: [nginx, "-g", "daemon off;"]
